/**
 * UI strings only.
 *
 * INITIAL_LEADS and INITIAL_TASKS used to live here and were seeded into every
 * new account, so demo people appeared as if they were real customers. Leads
 * and tasks now come from Postgres; a new account starts genuinely empty.
 */

export const TRANSLATIONS = {
  en: {
    appName: "AdToDeal AI",
    tagline: "Your Personal AI Sales & CRM Assistant",
    taglineDesc: "Follow up better, automate WhatsApp messages, close deals 3X faster, and never lose a lead again.",
    navDashboard: "Dashboard",
    navCRM: "Leads / CRM",
    navTasks: "Follow-up Tasks",
    navAIAssistant: "AI Sales Copilot",
    navWhatsApp: "WhatsApp Gen",
    navSocial: "Social Creator",
    navCampaigns: "Campaign Requests",
    navReports: "Reports / Analytics",
    navSubscription: "Subscriptions",
    navSettings: "Settings",
    navAdmin: "Admin Panel",
    navLogin: "Login",
    navRegister: "Register",
    navLogout: "Logout",
    langAr: "العربية",
    langEn: "English",

    // Dashboard
    totalLeads: "Total Leads",
    newLeads: "New Leads (Today)",
    dueFollowups: "Due Today",
    noResponse: "No Response",
    hotLeads: "Hot Leads",
    expectedValue: "Expected Pipeline Value",
    conversionRate: "Conversion Rate",
    bestSource: "Best Lead Source",
    weeklyActivity: "Weekly Activity Summary",
    salesPipeline: "Sales Pipeline Value",
    quickActions: "Quick Actions",
    recentLeads: "Recent Leads",
    addLead: "Add Lead",

    // CRM
    searchPlaceholder: "Search by name, phone or email...",
    filterStatus: "Filter Status",
    filterSource: "Filter Source",
    name: "Name",
    phone: "Phone",
    email: "Email",
    source: "Source",
    budget: "Budget",
    status: "Status",
    interestLevel: "Interest Level",
    all: "All",
    tabAllLeads: "All Leads",
    tabInterestedLeads: "Interested / Hot",
    tabFollowUpLeads: "Needs Follow-up",
    bulkWhatsAppCampaign: "Bulk WhatsApp Campaign",
    campaignProgress: "Campaign Progress",
    templateVariablesNotice: "Use variables {name} or {service} to customize",
    sendTo: "Send to",
    sent: "Sent",
    pending: "Pending",
    whatsappCampaignTitle: "WhatsApp Campaign Wizard",
    campaignRecipients: "Campaign Recipients",
    campaignTemplate: "Campaign Message Template",
    selectCampaignTemplate: "Select Campaign Template",
    noLeadsInSegment: "No leads in this segment to run a campaign.",
    closeCampaign: "Close Campaign",
    campaignSuccess: "Campaign completed!",

    // Lead details
    leadDetails: "Lead Details",
    lastContact: "Last Contact Date",
    nextFollowUp: "Next Follow-up Date",
    notes: "Lead Notes",
    expectedDealValue: "Expected Deal Value",
    interestedService: "Interested Product / Service",
    consentStatus: "Consent Status",
    whatsappAllowed: "WhatsApp Allowed",
    callsAllowed: "Calls Allowed",
    marketingAllowed: "Marketing Allowed",
    doNotContact: "Do Not Contact",
    unsubscribed: "Unsubscribed",
    editLead: "Edit Lead",
    deleteLead: "Delete Lead",
    saveChanges: "Save Changes",
    addNewNote: "Add a Note...",
    logAction: "Log Action",
    whatsappQuickMsg: "Send WhatsApp",
    callLead: "Call Lead",

    // AI Assistant
    aiAssistantTitle: "AI Sales Copilot",
    aiSubtitle: "Get instant follow-up prompts, objection responses, closing pitches, and call scripts for any product or service.",
    objectionHandler: "Objection Handler",
    callScriptGen: "Call Script Generator",
    selectObjection: "Select Lead Objection",
    objectionPrice: "Price is too expensive",
    objectionThink: "I need to think about it / consult partner",
    objectionRent: "Looking for alternative options",
    objectionLocation: "Need more time / info",
    generateResponse: "Generate AI Response",
    generateScript: "Generate Script",
    aiResponse: "AI Suggested Response",
    aiScript: "AI Call Script",
    suggestAction: "Suggest Next Action",

    // WhatsApp Message Gen
    whatsappTitle: "WhatsApp Message Generator",
    whatsappSubtitle: "Draft personalized client messages for any deal and open them instantly in WhatsApp.",
    selectTemplate: "Select Template",
    templateIntro: "First Introduction",
    templateFollowUp: "Soft Follow-up (No Response)",
    templateViewing: "Schedule Meeting / Presentation",
    templatePayment: "Payment Plan / Offer Details",
    templateObjection: "Addressing Price Objection",
    customMessage: "Custom Message",
    generateAndOpen: "Generate & Open WhatsApp",

    // Social Creator
    socialTitle: "Social Media Content Generator",
    socialSubtitle: "Create marketing posts, Reels scripts, catchy captions, and weekly content calendars for your business.",
    industry: "Industry",
    targetAudience: "Target Audience",
    serviceOrProduct: "Service/Product Focus",
    tone: "Tone of Voice",
    platform: "Platform",
    reelsScript: "Reels / TikTok Script",
    postIdeas: "Post Ideas & Captions",
    contentCalendar: "Weekly Content Calendar",
    generateContent: "Generate AI Content",

    // Campaign request
    campaignTitle: "Ad Campaign Request",
    campaignSubtitle: "Submit details to our marketing specialists to configure your custom lead gen ads.",
    platformSelect: "Choose Platforms",
    campaignGoal: "Campaign Goal",
    durationDays: "Duration (Days)",
    targetAge: "Target Age Group",
    targetInterests: "Target Interests",
    cityRegion: "City / Target Region",
    offerDetails: "Special Offer Details",
    specialNotes: "Additional Instructions",
    submitBrief: "Submit Brief",
    campaignsHistory: "Your Ad Briefs History",
    campaignPending: "Pending Review",
    campaignActive: "Active & Delivering",
    campaignCompleted: "Completed",

    // Subscription
    billingTitle: "Simple, Transparent Pricing",
    billingSubtitle: "Choose the plan that matches your current sales pipeline goals.",
    planBasic: "Basic Plan",
    planPro: "Pro Plan",
    planGrowth: "Growth Plan",
    currentPlan: "Current Plan",
    upgrade: "Upgrade Now",
    priceMonth: "/ month",
    featuresCRM: "Personal CRM Dashboard",
    featuresReminders: "Follow-up Notifications",
    featuresAILimited: "Limited AI Generation (20/mo)",
    featuresAIFull: "Unlimited AI Sales Copilot",
    featuresSocial: "Social Media Weekly Planner",
    featuresCampaigns: "Ad Campaign Brief Submissions",
    featuresReports: "Advanced Conversions Analytics",
    featuresSupport: "24/7 Priority WhatsApp Support",

    // Settings
    settingsTitle: "Account Settings",
    profileSettings: "Profile Information",
    companyName: "Business / Company Name",
    defaultLang: "Default System Language",
    whatsappNumber: "My WhatsApp Number",
    saveSettings: "Save Configuration",

    // Onboarding
    onboardingTitle: "Welcome to AdToDeal AI!",
    onboardingSubtitle: "Let's configure your digital sales assistant for your business domain.",
    step1: "Domain Setup",
    step2: "Target Audience",
    step3: "Assistant Personality",
    nextStep: "Next Step",
    prevStep: "Previous Step",
    finishSetup: "Finish & Launch Dashboard",

    // Admin Panel
    adminTitle: "Admin Administration Console",
    adminSubtitle: "Monitor all app activities, subscriptions, and active ad campaign briefs.",
    totalRegisteredUsers: "Total Registered Users",
    activeBriefs: "Active Ad Briefs",
    mrr: "Monthly Recurring Revenue",
    userList: "Registered Salespeople",
    briefList: "Submitted Campaign Briefs",
    approveBrief: "Approve & Launch",
    markCompleted: "Mark Completed",

    // Import Features
    importContacts: "Import from Contacts",
    importContactsDesc: "Import name, phone and email from your Phone or MacBook contacts",
    whatsappAnalyze: "Analyze WhatsApp Chat",
    whatsappAnalyzeDesc: "Paste a WhatsApp chat history to automatically fill client details using AI",
    pasteChatPlaceholder: "Paste WhatsApp conversation text here... \nExample:\nCustomer: Hello, I am interested in your software services.\nAgent: Hi! The package price is $1,500.\nCustomer: My budget is $1,200. Contact me at +966500000000.",
    analyzeBtn: "Analyze with AI",
    analyzingText: "AI is analyzing conversation...",
    analysisSuccess: "AI Analysis Complete! Form fields populated.",
    selectContactTitle: "Select Contact",
    mockContactsBook: "Mac / Phone Address Book",
    searchContacts: "Search contacts...",
    nativeContactsErr: "Device contacts API is not accessible in this browser. Showing Address Book backup.",
    aiSuggestions: "AI Suggestions for Sales Agent",
    aiSuggestionsPlaceholder: "AI recommendations will appear here after analysis...",
    openWhatsAppShortcut: "Open WhatsApp Web",
    whatsappUrlLabel: "WhatsApp Quick Link",

    // AI Assistant Chat Analysis
    chatAnalysisTab: "Chat Analysis",
    chatAnalysisDesc: "Paste a customer conversation transcript here to draft replies, extract requirements, or plan follow-up steps.",
    selectAnalysisQuestion: "Select AI Task",
    askReply: "Draft Suitable Reply",
    askRequirements: "Extract Requirements & Budget",
    askNextSteps: "Suggest Follow-up Action Plan",

    // AI Content Studio
    socialStudioTitle: "AI Content Creation Studio",
    socialStudioSubtitle: "Chat with the AI, upload offer specs, and instantly generate social posts, stories, videos, and client PDFs.",
    tabImage: "Design Image (Post/Story)",
    tabVideo: "Video Script & Mock",
    tabPDF: "Client PDF Booklet",
    tabCalendar: "Publish Calendar",
    uploadSpecs: "Attach Offer Specs / Product Data",
    uploadSuccess: "File parsed and data loaded successfully!",
    chatWithAI: "Chat with Content Creator Assistant",
    sendBtn: "Send & Update",
    draftPost: "Social Post Layout Preview",
    postFormat: "Format Ratio",
    postSquare: "Square Post (1:1)",
    postVertical: "Vertical Story (9:16)",
    videoScript: "Video Script & Captions",
    pdfBooklet: "Client PDF Booklet Preview",
    downloadDesign: "Download Visual Design (PNG)",
    downloadScript: "Export Video Script",
    downloadPDF: "Download Booklet PDF",
    suggestedQuestions: "Quick Creative Prompts",
    tabOverview: "Overview",
    tabFunnel: "Sales Funnel & Deals",
    tabSources: "Source ROI Insights",
    tabCampaigns: "Campaign Budgets",
    tabAIAnalyst: "AI Sales Analyst",
    generateAIReport: "Generate AI Performance Report",
    generatingAIReport: "AI is analyzing database...",
    aiReportTitle: "AI Strategic Sales Report",
    funnelNew: "New Leads",
    funnelContacted: "Contacted",
    funnelInterested: "Interested",
    funnelClose: "Close to Deal",
    funnelWon: "Won Deals",
    filterTimeframe: "Timeframe",
    filterBudget: "Budget Range",
    allBudgets: "All Budgets",
    lowBudget: "Under 50k",
    midBudget: "50k - 500k",
    highBudget: "Over 500k",
    cpl: "Cost per Lead (CPL)",
    roas: "Return on Ad Spend (ROAS)",
    totalAdSpend: "Total Ad Campaign Budget"
  },
  ar: {
    appName: "أد تو ديل AI",
    tagline: "مساعد المبيعات الشخصي الذكي",
    taglineDesc: "تابع عملائك بشكل أفضل، ولد رسائل الواتساب الفورية، وأغلق صفقاتك بسرعة 3X بدون ضياع أي عميل.",
    navDashboard: "لوحة التحكم",
    navCRM: "العملاء / CRM",
    navTasks: "مهام المتابعة",
    navAIAssistant: "مساعد المبيعات الذكي",
    navWhatsApp: "مولد الواتساب",
    navSocial: "صانع المحتوى",
    navCampaigns: "طلبات الحملات",
    navReports: "التقارير والتحليلات",
    navSubscription: "الاشتراكات",
    navSettings: "الإعدادات",
    navAdmin: "لوحة المسؤول",
    navLogin: "تسجيل الدخول",
    navRegister: "إنشاء حساب",
    navLogout: "تسجيل الخروج",
    langAr: "العربية",
    langEn: "English",

    // Dashboard
    totalLeads: "إجمالي العملاء",
    newLeads: "عملاء جدد (اليوم)",
    dueFollowups: "متابعات مستحقة اليوم",
    noResponse: "لم يرد",
    hotLeads: "عملاء نشطين جداً",
    expectedValue: "القيمة المتوقعة للمبيعات",
    conversionRate: "معدل التحويل",
    bestSource: "أفضل مصدر للعملاء",
    weeklyActivity: "ملخص النشاط الأسبوعي",
    salesPipeline: "قيمة المبيعات المحتملة",
    quickActions: "إجراءات سريعة",
    recentLeads: "العملاء المضافون حديثاً",
    addLead: "إضافة عميل جديد",

    // CRM
    searchPlaceholder: "ابحث بالاسم، الهاتف، أو البريد الإلكتروني...",
    filterStatus: "تصفية حسب الحالة",
    filterSource: "تصفية حسب المصدر",
    name: "الاسم",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    source: "المصدر",
    budget: "الميزانية",
    status: "الحالة",
    interestLevel: "مستوى الاهتمام",
    all: "الكل",
    tabAllLeads: "جميع العملاء",
    tabInterestedLeads: "العملاء المهتمين",
    tabFollowUpLeads: "عملاء المتابعة",
    bulkWhatsAppCampaign: "حملة واتساب جماعية",
    campaignProgress: "تقدم الحملة",
    templateVariablesNotice: "استخدم المتغيرات {name} أو {service} للتخصيص تلقائياً",
    sendTo: "إرسال إلى",
    sent: "تم الإرسال",
    pending: "قيد الانتظار",
    whatsappCampaignTitle: "مساعد حملات الواتساب الجماعية",
    campaignRecipients: "مستلمي الحملة الإعلانية",
    campaignTemplate: "نموذج رسالة الحملة",
    selectCampaignTemplate: "اختر قالب رسالة الحملة",
    noLeadsInSegment: "لا يوجد عملاء في هذا القسم لبدء حملة.",
    closeCampaign: "إغلاق الحملة",
    campaignSuccess: "اكتملت الحملة بنجاح!",

    // Lead details
    leadDetails: "تفاصيل العميل",
    lastContact: "تاريخ آخر تواصل",
    nextFollowUp: "تاريخ المتابعة التالية",
    notes: "ملاحظات العميل",
    expectedDealValue: "قيمة الصفقة المتوقعة",
    interestedService: "الخدمة / المنتج المهتم به",
    consentStatus: "حالة الموافقة على التواصل",
    whatsappAllowed: "يسمح بالواتساب",
    callsAllowed: "يسمح بالمكالمات",
    marketingAllowed: "يسمح بالتسويق",
    doNotContact: "عدم الاتصال نهائياً",
    unsubscribed: "ملغي الاشتراك",
    editLead: "تعديل العميل",
    deleteLead: "حذف العميل",
    saveChanges: "حفظ التغييرات",
    addNewNote: "إضافة ملاحظة...",
    logAction: "تسجيل إجراء",
    whatsappQuickMsg: "إرسال واتساب",
    callLead: "اتصال بالعميل",

    // AI Assistant
    aiAssistantTitle: "مساعد المبيعات بالذكاء الاصطناعي",
    aiSubtitle: "احصل على مقترحات للمتابعة، ردود على الاعتراضات، وسيناريوهات للمكالمات والعروض لأي مجال تجاري فوراً.",
    objectionHandler: "معالج الاعتراضات",
    callScriptGen: "مولد سيناريو المكالمات",
    selectObjection: "اختر اعتراض العميل",
    objectionPrice: "السعر مرتفع جداً مقارنة بالميزانية",
    objectionThink: "أحتاج للتفكير / استشارة شريكي",
    objectionRent: "البحث عن بدائل أو تأجيل القرار",
    objectionLocation: "أحتاج مزيداً من المعلومات للتأكد",
    generateResponse: "توليد الرد بالذكاء الاصطناعي",
    generateScript: "توليد السيناريو",
    aiResponse: "الرد المقترح من المساعد الذكي",
    aiScript: "سيناريو المكالمة المقترح",
    suggestAction: "اقتراح الإجراء التالي",

    // WhatsApp Message Gen
    whatsappTitle: "مولد رسائل الواتساب",
    whatsappSubtitle: "صغ رسائل مخصصة لعملائك وافتحها مباشرة في تطبيق الواتساب بضغطة زر لأي صفقة.",
    selectTemplate: "اختر قالب الرسالة",
    templateIntro: "التعريف الأول بالخدمة / المنتج",
    templateFollowUp: "متابعة لطيفة (عدم رد)",
    templateViewing: "جدولة موعد اجتماع أو عرض تقديمى",
    templatePayment: "تفاصيل خطة الأسعار والعرض",
    templateObjection: "الرد على اعتراض السعر مرتفع",
    customMessage: "رسالة مخصصة",
    generateAndOpen: "توليد وفتح واتساب",

    // Social Creator
    socialTitle: "صانع محتوى شبكات التواصل الاجتماعي",
    socialSubtitle: "أنشئ منشورات تسويقية، سيناريوهات فيديوهات ريلز، تعليقات جذابة، وتقويم محتوى أسبوعي كامل لمبيعاتك.",
    industry: "مجال العمل / النشاط",
    targetAudience: "الجمهور المستهدف",
    serviceOrProduct: "الخدمة / المنتج المستهدف",
    tone: "نبرة الصوت للذكاء الاصطناعي",
    platform: "المنصة",
    reelsScript: "سكربت ريلز / تيك توك",
    postIdeas: "أفكار منشورات وتعليقات",
    contentCalendar: "تقويم محتوى أسبوعي",
    generateContent: "توليد المحتوى بالذكاء الاصطناعي",

    // Campaign request
    campaignTitle: "طلب حملة إعلانية ممولة",
    campaignSubtitle: "أرسل تفاصيل مشروعك وميزانيتك الإعلانية ليقوم خبراء التسويق لدينا بإطلاق حملاتك الممولة.",
    platformSelect: "اختر المنصات الإعلانية",
    campaignGoal: "هدف الحملة الإعلانية",
    durationDays: "مدة الحملة (بالأيام)",
    targetAge: "الفئة العمرية المستهدفة",
    targetInterests: "الاهتمامات المستهدفة",
    cityRegion: "المدينة / المنطقة المستهدفة",
    offerDetails: "تفاصيل العرض الخاص",
    specialNotes: "تعليمات إضافية",
    submitBrief: "إرسال طلب الحملة",
    campaignsHistory: "سجل طلباتك الإعلانية",
    campaignPending: "قيد المراجعة",
    campaignActive: "نشطة وتجلب عملاء",
    campaignCompleted: "مكتملة",

    // Subscription
    billingTitle: "أسعار بسيطة وشفافة",
    billingSubtitle: "اختر الباقة المناسبة لحجم مبيعاتك وأهداف نشاطك التجاري.",
    planBasic: "الباقة الأساسية",
    planPro: "الباقة الاحترافية (Pro)",
    planGrowth: "باقة النمو (Growth)",
    currentPlan: "باقتك الحالية",
    upgrade: "ترقية الآن",
    priceMonth: "/ شهرياً",
    featuresCRM: "لوحة CRM لإدارة العملاء",
    featuresReminders: "تنبيهات وتذكيرات المتابعة",
    featuresAILimited: "توليد ذكاء اصطناعي محدود (20 شهرياً)",
    featuresAIFull: "مساعد مبيعات ذكي غير محدود 24/7",
    featuresSocial: "جدولة وصناعة محتوى تواصل أسبوعي",
    featuresCampaigns: "إمكانية تقديم طلبات إعلانات ممولة",
    featuresReports: "تقارير وتحليلات أداء المبيعات",
    featuresSupport: "دعم فني أولوية عبر الواتساب",

    // Settings
    settingsTitle: "إعدادات الحساب",
    profileSettings: "بيانات الملف الشخصي",
    companyName: "اسم الشركة / النشاط التجاري",
    defaultLang: "لغة النظام الافتراضية",
    whatsappNumber: "رقم الواتساب الخاص بي",
    saveSettings: "حفظ الإعدادات",

    // Onboarding
    onboardingTitle: "مرحباً بك في أد تو ديل AI!",
    onboardingSubtitle: "لنقم بإعداد مساعدك الرقمي المخصص لمجال مبيعاتك ونشاطك التجارى.",
    step1: "إعداد مجال العمل",
    step2: "الجمهور المستهدف",
    step3: "شخصية المساعد",
    nextStep: "الخطوة التالية",
    prevStep: "الخطوة السابقة",
    finishSetup: "إنهاء وبدء الاستخدام",

    // Admin Panel
    adminTitle: "لوحة إحصائيات الأدمن",
    adminSubtitle: "متابعة كافة أنشطة المستخدمين، الاشتراكات، وطلبات الحملات الإعلانية النشطة.",
    totalRegisteredUsers: "إجمالي رجال المبيعات والشركات",
    activeBriefs: "طلبات الحملات النشطة",
    mrr: "الإيرادات الشهرية المتكررة",
    userList: "قائمة المستخدمين",
    briefList: "طلبات الحملات المقدمة",
    approveBrief: "موافقة وإطلاق",
    markCompleted: "تحديد كمكتملة",

    // Import Features
    importContacts: "استيراد من جهات الاتصال",
    importContactsDesc: "استيراد الاسم، الهاتف، والبريد من سجل هاتفك أو جهازك بكبسة زر",
    whatsappAnalyze: "تحليل محادثة واتساب",
    whatsappAnalyzeDesc: "الصق نص محادثة الواتساب لتعبئة بيانات العميل وتوصيات المتابعة تلقائياً",
    pasteChatPlaceholder: "الصق نص محادثة الواتساب هنا... \nمثال:\nالعميل: السلام عليكم، حابب أعرف تفاصيل الخدمة والأسعار.\nالمبيعات: وعليكم السلام، سعر الحزمة 5000 ريال.\nالعميل: ميزانيتي 4500 ريال، تواصل معي على +966500000000.",
    analyzeBtn: "تحليل بالذكاء الاصطناعي",
    analyzingText: "جاري تحليل المحادثة بواسطة الذكاء الاصطناعي...",
    analysisSuccess: "تم اكتمال التحليل وتعبئة البيانات بنجاح!",
    selectContactTitle: "اختر جهة اتصال",
    mockContactsBook: "سجل جهات الاتصال",
    searchContacts: "ابحث في جهات الاتصال...",
    nativeContactsErr: "تعذر فتح جهات اتصال الجهاز المباشرة. يتم عرض سجل جهات الاتصال الاحتياطي.",
    aiSuggestions: "توصيات الذكاء الاصطناعي لرجال المبيعات",
    aiSuggestionsPlaceholder: "ستظهر المقترحات هنا بعد التحليل...",
    openWhatsAppShortcut: "فتح الواتساب ويب",
    whatsappUrlLabel: "رابط الواتساب السريع",

    // AI Assistant Chat Analysis
    chatAnalysisTab: "تحليل المحادثات",
    chatAnalysisDesc: "الصق نص محادثتك مع العميل لصياغة رد مقنع، استخراج الميزانية المتوقعة، أو تخطيط خطة المتابعة.",
    selectAnalysisQuestion: "اختر مهمة الذكاء الاصطناعي",
    askReply: "صياغة رد مناسب ومقنع",
    askRequirements: "استخراج الميزانية المتوقعة والاحتياجات",
    askNextSteps: "اقترح خطة عمل للمتابعة",

    // AI Content Studio
    socialStudioTitle: "استوديو صناعة المحتوى التسويقي",
    socialStudioSubtitle: "تحدث مع الذكاء الاصطناعي، ارفق بيانات عروضك وخدماتك، واصنع منشورات، ريلز، وملفات PDF لعملائك فوراً.",
    tabImage: "تصميم صورة (بوست/ستوري)",
    tabVideo: "سكربت ومعاينة فيديو",
    tabPDF: "ملف PDF للعملاء",
    tabCalendar: "جدول النشر الأسبوعي",
    uploadSpecs: "إرفاق مواصفات العرض / تفاصيل المنتج",
    uploadSuccess: "تم رفع وتحليل البيانات بنجاح!",
    chatWithAI: "المحادثة مع صانع المحتوى الذكي",
    sendBtn: "إرسال وتحديث",
    draftPost: "معاينة تصميم المنشور",
    postFormat: "أبعاد التصميم",
    postSquare: "بوست مربّع (1:1)",
    postVertical: "ستوري عمودي (9:16)",
    videoScript: "سكربت الفيديو والتعليقات",
    pdfBooklet: "معاينة ملف الـ PDF للعميل",
    downloadDesign: "تحميل التصميم (PNG)",
    downloadScript: "تصدير سكربت الفيديو",
    downloadPDF: "تحميل ملف הـ PDF",
    suggestedQuestions: "مقترحات إبداعية سريعة",
    tabOverview: "نظرة عامة",
    tabFunnel: "مسار المبيعات والصفقات",
    tabSources: "تحليل عائد مصادر العملاء",
    tabCampaigns: "ميزانيات الحملات",
    tabAIAnalyst: "محلل المبيعات الذكي",
    generateAIReport: "توليد تقرير أداء بالذكاء الاصطناعي",
    generatingAIReport: "جاري تحليل قنوات المبيعات...",
    aiReportTitle: "التقرير الاستراتيجي لأداء المبيعات",
    funnelNew: "عملاء جدد",
    funnelContacted: "تم التواصل",
    funnelInterested: "مهتمين",
    funnelClose: "قريب من التوقيع",
    funnelWon: "صفقات ناجحة",
    filterTimeframe: "الفترة الزمنية",
    filterBudget: "نطاق الميزانية",
    allBudgets: "جميع الميزانيات",
    lowBudget: "أقل من 50 ألف",
    midBudget: "50 - 500 ألف",
    highBudget: "أكثر من 500 ألف",
    cpl: "تكلفة العميل المحتمل (CPL)",
    roas: "العائد على الإنفاق الإعلاني (ROAS)",
    totalAdSpend: "إجمالي ميزانية الحملات الإعلانية"
  }
};
