export const INITIAL_LEADS = [
  {
    id: '1',
    name: 'Ahmad Al-Saeed',
    nameAr: 'أحمد السعيد',
    phone: '+966501234567',
    email: 'ahmad@example.com',
    source: 'Instagram Ad',
    sourceAr: 'إعلان إنستغرام',
    service: '3-Bedroom Apartment in Downtown Riyadh',
    serviceAr: 'شقة 3 غرف في وسط الرياض',
    budget: 850000,
    status: 'Interested', // New, Contacted, Interested, Needs Follow-up, No Response, Postponed, Close to Deal, Won, Lost, Not Interested
    statusAr: 'مهتم',
    lastContact: '2026-06-01',
    nextFollowUp: '2026-06-04',
    notes: 'Very interested in the payment plan. Prefers WhatsApp over phone calls during working hours.',
    notesAr: 'مهتم جداً بخطة الدفع. يفضل الواتساب على المكالمات الهاتفية خلال ساعات العمل.',
    interestLevel: 'High', // High, Medium, Low
    interestLevelAr: 'عالي',
    expectedValue: 850000,
    consent: {
      whatsapp: true,
      calls: true,
      marketing: true
    }
  },
  {
    id: '2',
    name: 'Sarah Connor',
    nameAr: 'سارة كونر',
    phone: '+971509876543',
    email: 'sarah.c@example.com',
    source: 'Referral',
    sourceAr: 'توصية / صديق',
    service: 'Luxury Villa in Dubai Hills',
    serviceAr: 'فيلا فاخرة في دبي هيلز',
    budget: 4200000,
    status: 'Close to Deal',
    statusAr: 'قريب من إتمام الصفقة',
    lastContact: '2026-06-02',
    nextFollowUp: '2026-06-03',
    notes: 'Completed the site viewing. Contract is being prepared. Needs follow up today for deposit details.',
    notesAr: 'أكملت معاينة الموقع. يتم تحضير العقد. بحاجة للمتابعة اليوم بخصوص تفاصيل العربون.',
    interestLevel: 'High',
    interestLevelAr: 'عالي',
    expectedValue: 4200000,
    consent: {
      whatsapp: true,
      calls: true,
      marketing: false
    }
  },
  {
    id: '3',
    name: 'Youssef Mansour',
    nameAr: 'يوسف منصور',
    phone: '+966551122334',
    email: 'youssef@example.com',
    source: 'Facebook Lead',
    sourceAr: 'إعلان فيسبوك',
    service: '2-Bedroom Townhouse in Yas Island',
    serviceAr: 'تاون هاوس غرفتين في جزيرة ياس',
    budget: 1500000,
    status: 'New',
    statusAr: 'جديد',
    lastContact: '2026-06-03',
    nextFollowUp: '2026-06-05',
    notes: 'Just registered. Wants to receive brochures of upcoming projects.',
    notesAr: 'سجل للتو. يريد استلام الكتيبات الخاصة بالمشاريع القادمة.',
    interestLevel: 'Medium',
    interestLevelAr: 'متوسط',
    expectedValue: 1500000,
    consent: {
      whatsapp: true,
      calls: false,
      marketing: true
    }
  },
  {
    id: '4',
    name: 'Lina Haddad',
    nameAr: 'لينا حداد',
    phone: '+962791234567',
    email: 'lina.h@example.com',
    source: 'Google Search',
    sourceAr: 'بحث جوجل',
    service: 'Office Space in Amman',
    serviceAr: 'مساحة مكتبية في عمان',
    budget: 350000,
    status: 'Needs Follow-up',
    statusAr: 'بحاجة لمتابعة',
    lastContact: '2026-05-28',
    nextFollowUp: '2026-06-03',
    notes: 'Inquired about rental yields. Needs follow-up message about high-ROI commercial properties.',
    notesAr: 'استفسرت عن عوائد الإيجار. بحاجة لرسالة متابعة حول العقارات التجارية ذات العائد المرتفع.',
    interestLevel: 'Medium',
    interestLevelAr: 'متوسط',
    expectedValue: 350000,
    consent: {
      whatsapp: true,
      calls: true,
      marketing: true
    }
  },
  {
    id: '5',
    name: 'Mohammad Al-Otaibi',
    nameAr: 'محمد العتيبي',
    phone: '+966567788990',
    email: 'm.otaibi@example.com',
    source: 'TikTok Campaign',
    sourceAr: 'حملة تيك توك',
    service: 'Land Plot in North Riyadh',
    serviceAr: 'أرض سكنية شمال الرياض',
    budget: 2100000,
    status: 'No Response',
    statusAr: 'لا يوجد رد',
    lastContact: '2026-05-25',
    nextFollowUp: '2026-06-06',
    notes: 'Did not answer 3 follow-up calls. Send soft WhatsApp follow-up reminder.',
    notesAr: 'لم يرد على 3 مكالمات متابعة. أرسل رسالة تذكير لطيفة عبر الواتساب.',
    interestLevel: 'Low',
    interestLevelAr: 'منخفض',
    expectedValue: 2100000,
    consent: {
      whatsapp: true,
      calls: true,
      marketing: false
    }
  },
  {
    id: '6',
    name: 'Fatima Al-Zahrani',
    nameAr: 'فاطمة الزهراني',
    phone: '+966504433221',
    email: 'fatima.z@example.com',
    source: 'Direct Visit',
    sourceAr: 'زيارة مباشرة للمكتب',
    service: 'Penthouse in Jeddah Waterfront',
    serviceAr: 'بنتهاوس في واجهة جدة البحرية',
    budget: 6800000,
    status: 'Won',
    statusAr: 'تم الفوز بها',
    lastContact: '2026-05-30',
    nextFollowUp: '',
    notes: 'Deal closed! Down payment received, contract signed. Welcome pack sent.',
    notesAr: 'تمت الصفقة! تم استلام الدفعة الأولى، وتوقيع العقد. تم إرسال حزمة الترحيب.',
    interestLevel: 'High',
    interestLevelAr: 'عالي',
    expectedValue: 6800000,
    consent: {
      whatsapp: true,
      calls: true,
      marketing: true
    }
  }
];

export const INITIAL_TASKS = [
  { id: 't1', leadId: '2', title: 'Prepare sales agreement for Sarah Connor', titleAr: 'تجهيز اتفاقية البيع لسارة كونر', dueDate: '2026-06-03', completed: false, priority: 'High' },
  { id: 't2', leadId: '4', title: 'Send commercial investment reports to Lina Haddad', titleAr: 'إرسال تقارير الاستثمار التجاري للينا حداد', dueDate: '2026-06-03', completed: false, priority: 'Medium' },
  { id: 't3', leadId: '5', title: 'Send follow-up WhatsApp message to Mohammad Al-Otaibi', titleAr: 'إرسال رسالة متابعة واتساب لمحمد العتيبي', dueDate: '2026-06-04', completed: false, priority: 'Low' },
  { id: 't4', leadId: '1', title: 'Share payment plans PDF with Ahmad Al-Saeed', titleAr: 'مشاركة ملف خطط الدفع PDF مع أحمد السعيد', dueDate: '2026-06-04', completed: false, priority: 'High' },
  { id: 't5', leadId: '3', title: 'Initial discovery call with Youssef Mansour', titleAr: 'مكالمة الاستكشاف الأولية مع يوسف منصور', dueDate: '2026-06-05', completed: false, priority: 'Medium' }
];

export const TRANSLATIONS = {
  en: {
    appName: "SalesMate AI",
    tagline: "Your Personal Sales Assistant",
    taglineDesc: "Follow up better, sell more, and never lose a lead again.",
    navDashboard: "Dashboard",
    navCRM: "Leads / CRM",
    navTasks: "Follow-up Tasks",
    navAIAssistant: "AI Assistant",
    navWhatsApp: "WhatsApp Gen",
    navSocial: "Social Creator",
    navCampaigns: "Campaign Requests",
    navReports: "Reports / Analytics",
    navSubscription: "Subscriptions",
    navSettings: "Settings",
    navAdmin: "Admin Panel",
    navLogin: "Login",
    navRegister: "Register",
    navLogout: "Logout",
    langAr: "العربية",
    langEn: "English",

    // Dashboard
    totalLeads: "Total Leads",
    newLeads: "New Leads (Today)",
    dueFollowups: "Due Today",
    noResponse: "No Response",
    hotLeads: "Hot Leads",
    expectedValue: "Expected Value",
    conversionRate: "Conversion Rate",
    bestSource: "Best Lead Source",
    weeklyActivity: "Weekly Activity Summary",
    salesPipeline: "Sales Pipeline Value",
    quickActions: "Quick Actions",
    recentLeads: "Recent Leads",
    addLead: "Add Lead",

    // CRM
    searchPlaceholder: "Search by name, phone or email...",
    filterStatus: "Filter Status",
    filterSource: "Filter Source",
    name: "Name",
    phone: "Phone",
    email: "Email",
    source: "Source",
    budget: "Budget",
    status: "Status",
    interestLevel: "Interest Level",
    actions: "Actions",
    all: "All",

    // Lead details
    leadDetails: "Lead Details",
    lastContact: "Last Contact Date",
    nextFollowUp: "Next Follow-up Date",
    notes: "Lead Notes",
    expectedDealValue: "Expected Deal Value",
    interestedService: "Interested Service / Property",
    consentStatus: "Consent Status",
    whatsappAllowed: "WhatsApp Allowed",
    callsAllowed: "Calls Allowed",
    marketingAllowed: "Marketing Allowed",
    doNotContact: "Do Not Contact",
    unsubscribed: "Unsubscribed",
    editLead: "Edit Lead",
    deleteLead: "Delete Lead",
    saveChanges: "Save Changes",
    addNewNote: "Add a Note...",
    logAction: "Log Action",
    whatsappQuickMsg: "Send WhatsApp",
    callLead: "Call Lead",

    // AI Assistant
    aiAssistantTitle: "AI Sales Assistant",
    aiSubtitle: "Get instant follow-up prompts, objection responses, and call scripts.",
    objectionHandler: "Objection Handler",
    callScriptGen: "Call Script Generator",
    selectObjection: "Select Lead Objection",
    objectionPrice: "Price is too expensive",
    objectionThink: "I need to think about it / consult partner",
    objectionRent: "Renting is better than buying right now",
    objectionLocation: "Location is too far",
    generateResponse: "Generate AI Response",
    generateScript: "Generate Script",
    aiResponse: "AI Suggested Response",
    aiScript: "AI Call Script",
    suggestAction: "Suggest Next Action",

    // WhatsApp Message Gen
    whatsappTitle: "WhatsApp Message Generator",
    whatsappSubtitle: "Draft personalized client messages and open them instantly in WhatsApp.",
    selectTemplate: "Select Template",
    templateIntro: "First Introduction",
    templateFollowUp: "Soft Follow-up (No Response)",
    templateViewing: "Schedule Site Viewing",
    templatePayment: "Payment Plan Details",
    templateObjection: "Addressing Price Objection",
    customMessage: "Custom Message",
    generateAndOpen: "Generate & Open WhatsApp",

    // Social Creator
    socialTitle: "Social Media Content Generator",
    socialSubtitle: "Create property tips, area guides, captions, and calendars.",
    industry: "Industry",
    targetAudience: "Target Audience",
    serviceOrProduct: "Service/Product Focus",
    tone: "Tone of Voice",
    platform: "Platform",
    reelsScript: "Reels / TikTok Script",
    postIdeas: "Post Ideas & Captions",
    contentCalendar: "Weekly Content Calendar",
    generateContent: "Generate AI Content",

    // Campaign request
    campaignTitle: "Ad Campaign Request",
    campaignSubtitle: "Submit details to our marketing specialists to configure your custom lead gen ads.",
    platformSelect: "Choose Platforms",
    campaignGoal: "Campaign Goal",
    durationDays: "Duration (Days)",
    targetAge: "Target Age Group",
    targetInterests: "Target Interests",
    cityRegion: "City / Target Region",
    offerDetails: "Special Offer Details",
    specialNotes: "Additional Instructions",
    submitBrief: "Submit Brief",
    campaignsHistory: "Your Ad Briefs History",
    campaignPending: "Pending Review",
    campaignActive: "Active & Delivering",
    campaignCompleted: "Completed",

    // Subscription
    billingTitle: "Simple, Transparent Pricing",
    billingSubtitle: "Choose the plan that matches your current sales pipeline goals.",
    planBasic: "Basic Plan",
    planPro: "Pro Plan",
    planGrowth: "Growth Plan",
    currentPlan: "Current Plan",
    upgrade: "Upgrade Now",
    priceMonth: "/ month",
    featuresCRM: "Personal CRM Dashboard",
    featuresReminders: "Follow-up Notifications",
    featuresAILimited: "Limited AI Generation (20/mo)",
    featuresAIFull: "Unlimited AI Personal Assistant",
    featuresSocial: "Social Media Weekly Planner",
    featuresCampaigns: "Ad Campaign Brief Submissions",
    featuresReports: "Advanced Conversions Analytics",
    featuresSupport: "24/7 Priority WhatsApp Support",

    // Settings
    settingsTitle: "Account Settings",
    profileSettings: "Profile Information",
    companyName: "Agency / Company Name",
    defaultLang: "Default System Language",
    whatsappNumber: "My WhatsApp Number",
    saveSettings: "Save Configuration",

    // Onboarding
    onboardingTitle: "Welcome to SalesMate AI!",
    onboardingSubtitle: "Let's configure your digital assistant for your sales domain.",
    step1: "Domain Setup",
    step2: "Target Audience",
    step3: "Assistant Personality",
    nextStep: "Next Step",
    prevStep: "Previous Step",
    finishSetup: "Finish & Launch Dashboard",

    // Admin Panel
    adminTitle: "Admin Administration Console",
    adminSubtitle: "Monitor all app activities, subscriptions, and active ad campaign briefs.",
    totalRegisteredUsers: "Total Registered Users",
    activeBriefs: "Active Ad Briefs",
    mrr: "Monthly Recurring Revenue",
    userList: "Registered Salespeople",
    briefList: "Submitted Campaign Briefs",
    approveBrief: "Approve & Launch",
    markCompleted: "Mark Completed"
  },
  ar: {
    appName: "سيلز ميت AI",
    tagline: "مساعد المبيعات الشخصي الذكي",
    taglineDesc: "تابع عملائك بشكل أفضل، وزد مبيعاتك، ولا تفقد أي عميل محتمل بعد اليوم.",
    navDashboard: "لوحة التحكم",
    navCRM: "العملاء / CRM",
    navTasks: "مهام المتابعة",
    navAIAssistant: "المساعد الذكي",
    navWhatsApp: "مولد الواتساب",
    navSocial: "صانع المحتوى",
    navCampaigns: "طلبات الحملات",
    navReports: "التقارير والتحليلات",
    navSubscription: "الاشتراكات",
    navSettings: "الإعدادات",
    navAdmin: "لوحة المسؤول",
    navLogin: "تسجيل الدخول",
    navRegister: "إنشاء حساب",
    navLogout: "تسجيل الخروج",
    langAr: "العربية",
    langEn: "English",

    // Dashboard
    totalLeads: "إجمالي العملاء",
    newLeads: "عملاء جدد (اليوم)",
    dueFollowups: "متابعات مستحقة اليوم",
    noResponse: "لم يرد",
    hotLeads: "عملاء نشطين جداً",
    expectedValue: "القيمة المتوقعة للمبيعات",
    conversionRate: "معدل التحويل",
    bestSource: "أفضل مصدر للعملاء",
    weeklyActivity: "ملخص النشاط الأسبوعي",
    salesPipeline: "قيمة المبيعات المحتملة",
    quickActions: "إجراءات سريعة",
    recentLeads: "العملاء المضافون حديثاً",
    addLead: "إضافة عميل جديد",

    // CRM
    searchPlaceholder: "ابحث بالاسم، الهاتف، أو البريد الإلكتروني...",
    filterStatus: "تصفية حسب الحالة",
    filterSource: "تصفية حسب المصدر",
    name: "الاسم",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    source: "المصدر",
    budget: "الميزانية",
    status: "الحالة",
    interestLevel: "مستوى الاهتمام",
    actions: "الإجراءات",
    all: "الكل",

    // Lead details
    leadDetails: "تفاصيل العميل",
    lastContact: "تاريخ آخر تواصل",
    nextFollowUp: "تاريخ المتابعة التالية",
    notes: "ملاحظات العميل",
    expectedDealValue: "قيمة الصفقة المتوقعة",
    interestedService: "الخدمة / العقار المهتم به",
    consentStatus: "حالة الموافقة على التواصل",
    whatsappAllowed: "يسمح بالواتساب",
    callsAllowed: "يسمح بالمكالمات",
    marketingAllowed: "يسمح بالتسويق",
    doNotContact: "عدم الاتصال نهائياً",
    unsubscribed: "ملغي الاشتراك",
    editLead: "تعديل العميل",
    deleteLead: "حذف العميل",
    saveChanges: "حفظ التغييرات",
    addNewNote: "إضافة ملاحظة...",
    logAction: "تسجيل إجراء",
    whatsappQuickMsg: "إرسال واتساب",
    callLead: "اتصال بالعميل",

    // AI Assistant
    aiAssistantTitle: "مساعد المبيعات بالذكاء الاصطناعي",
    aiSubtitle: "احصل على مقترحات للمتابعة، ردود على الاعتراضات، وسيناريوهات للمكالمات فوراً.",
    objectionHandler: "معالج الاعتراضات",
    callScriptGen: "مولد سيناريو المكالمات",
    selectObjection: "اختر اعتراض العميل",
    objectionPrice: "السعر مرتفع جداً",
    objectionThink: "أحتاج للتفكير / استشارة شريكي",
    objectionRent: "الإيجار أفضل من الشراء بالوقت الحالي",
    objectionLocation: "الموقع بعيد جداً",
    generateResponse: "توليد الرد بالذكاء الاصطناعي",
    generateScript: "توليد السيناريو",
    aiResponse: "الرد المقترح من المساعد الذكي",
    aiScript: "سيناريو المكالمة المقترح",
    suggestAction: "اقتراح الإجراء التالي",

    // WhatsApp Message Gen
    whatsappTitle: "مولد رسائل الواتساب",
    whatsappSubtitle: "صغ رسائل مخصصة لعملائك وافتحها مباشرة في تطبيق الواتساب بضغطة زر.",
    selectTemplate: "اختر قالب الرسالة",
    templateIntro: "التعريف الأول بالخدمة",
    templateFollowUp: "متابعة لطيفة (عدم رد)",
    templateViewing: "جدولة موعد معاينة موقع",
    templatePayment: "تفاصيل خطة الدفع",
    templateObjection: "الرد على اعتراض السعر مرتفع",
    customMessage: "رسالة مخصصة",
    generateAndOpen: "توليد وفتح واتساب",

    // Social Creator
    socialTitle: "صانع محتوى شبكات التواصل الاجتماعي",
    socialSubtitle: "أنشئ نصائح عقارية، أدلة مناطق، تعليقات جذابة، وتقويم محتوى أسبوعي كامل.",
    industry: "مجال العمل",
    targetAudience: "الجمهور المستهدف",
    serviceOrProduct: "الخدمة / المنتج المستهدف",
    tone: "نبرة الصوت للذكاء الاصطناعي",
    platform: "المنصة المستهدفة",
    reelsScript: "سيناريو ريلز / تيك توك",
    postIdeas: "أفكار المنشورات والتعليقات",
    contentCalendar: "جدول المحتوى الأسبوعي",
    generateContent: "توليد المحتوى بالذكاء الاصطناعي",

    // Campaign request
    campaignTitle: "طلب حملة إعلانية ممولة",
    campaignSubtitle: "أرسل تفاصيل حملتك التسويقية لخبراءنا ليقوموا بضبط وتفعيل الإعلانات المخصصة لك لجلب عملاء.",
    platformSelect: "اختر المنصات الإعلانية",
    campaignGoal: "هدف الحملة",
    durationDays: "مدة الحملة (بالأيام)",
    targetAge: "الفئة العمرية المستهدفة",
    targetInterests: "الاهتمامات المستهدفة",
    cityRegion: "المدينة / المنطقة المستهدفة",
    offerDetails: "تفاصيل العرض الخاص",
    specialNotes: "ملاحظات وإرشادات إضافية",
    submitBrief: "تقديم الطلب والموجز الإعلاني",
    campaignsHistory: "سجل طلبات حملاتك الإعلانية",
    campaignPending: "قيد المراجعة والتدقيق",
    campaignActive: "نشطة وتجلب عملاء",
    campaignCompleted: "مكتملة",

    // Subscription
    billingTitle: "أسعار بسيطة وشفافة للجميع",
    billingSubtitle: "اختر الخطة المناسبة لحجم مبيعاتك وأهدافك التسويقية.",
    planBasic: "الخطة الأساسية",
    planPro: "الخطة الاحترافية",
    planGrowth: "خطة النمو والريادة",
    currentPlan: "خطتك الحالية",
    upgrade: "ترقية الاشتراك الآن",
    priceMonth: "/ شهرياً",
    featuresCRM: "نظام إدارة علاقات العملاء CRM كامل",
    featuresReminders: "تذكيرات وإشعارات للمتابعة اليومية",
    featuresAILimited: "توليد ذكاء اصطناعي محدود (20 شهرياً)",
    featuresAIFull: "مساعد شخصي ذكي غير محدود 24/7",
    featuresSocial: "جدولة وصناعة محتوى تواصل اجتماعي أسبوعي",
    featuresCampaigns: "إمكانية إرسال طلبات الحملات الإعلانية",
    featuresReports: "تحليلات متقدمة لنسب تحويل المبيعات",
    featuresSupport: "دعم فني ذو أولوية عبر الواتساب",

    // Settings
    settingsTitle: "إعدادات الحساب",
    profileSettings: "بيانات الحلف والملف الشخصي",
    companyName: "اسم الوكالة / الشركة العقارية",
    defaultLang: "لغة النظام الافتراضية",
    whatsappNumber: "رقم الواتساب الخاص بي",
    saveSettings: "حفظ الإعدادات",

    // Onboarding
    onboardingTitle: "مرحباً بك في سيلز ميت AI!",
    onboardingSubtitle: "دعنا نقوم بتهيئة مساعدك الرقمي ليتناسب مع أسلوب ومجال عملك.",
    step1: "إعداد مجال العمل",
    step2: "الجمهور المستهدف",
    step3: "شخصية المساعد الذكي",
    nextStep: "الخطوة التالية",
    prevStep: "الخطوة السابقة",
    finishSetup: "إنهاء التهيئة وتشغيل لوحة التحكم",

    // Admin Panel
    adminTitle: "لوحة التحكم والإشراف للمسؤول",
    adminSubtitle: "تابع إحصائيات التطبيق، طلبات الحملات النشطة، والاشتراكات الحالية.",
    totalRegisteredUsers: "إجمالي المشتركين المسجلين",
    activeBriefs: "الحملات الإعلانية المطلوبة",
    mrr: "الإيرادات الشهرية المتكررة",
    userList: "المسوقين المسجلين",
    briefList: "طلبات الحملات الإعلانية المقدمة",
    approveBrief: "الموافقة والتشغيل",
    markCompleted: "تحديد كمكتمل"
  }
};
